apiVersion: v1
kind: Service
metadata:
  name: kck-ipa-repeatable-lab-web-service
  namespace: ipa2025
spec:
  selector:
    app: kck-ipa-repeatable-lab-web
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP