---
- name: Create Loopback Interface on Cisco Router
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_ssh_common_args: "-oKexAlgorithms=+diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-rsa"

  tasks:
    - name: Configure Loopback Interface
      ios_config:
        lines:
          - interface Loopback{{ loopback_number }}
          - ip address {{ loopback_ip }} 255.255.255.255