name: CI Pipeline

on:
  push:
    branches: [test-instruc]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3

    - name: Install Lint & Format Tools
      run: |
        pip install flake8 black

    - name: Run flake8 (Lint)
      run: flake8 .

    - name: Check code format with black
      run: black --check .

